In [4]:
import numpy as np

In [6]:
angka = [1,2,3]

In [8]:
angkanp = np.array(angka)

In [12]:
angkanp

array([1, 2, 3])

In [16]:
angka*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [26]:
angkanp*3

array([3, 6, 9])

In [28]:
versilist = [[1,2,3], [4,5,6], [7,8,9]]
versilist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [26]:
versinumpy = np.array(versilist)
versinumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,20,3) # bilangan dari 0 sampai 20 kelipatan 3

array([ 0,  3,  6,  9, 12, 15, 18])

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [46]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.linspace(0,8,10) 
#bilangan dari 0 sampai 8 dibagi 10 bilangan

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [68]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])