In [15]:
import numpy as np 

In [179]:
angka = np.arange(0,11)

In [181]:
angka

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [183]:
angka[5]

5

In [185]:
angka[5:9] # mengurutkan dari angka 5 sampe 8

array([5, 6, 7, 8])

In [193]:
angka[5:] 

array([ 5,  6,  7,  8,  9, 10])

In [203]:
angka[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [231]:
angka2 = angka[:6] #tambahkan copy jika ingin mempertahankan nilai tetap pada angka1

In [233]:
angka2

array([200, 200, 200, 200, 200, 200])

In [235]:
angka2[:] = 200

In [237]:
angka2

array([200, 200, 200, 200, 200, 200])

In [239]:
angka

array([200, 200, 200, 200, 200, 200,   6,   7,   8,   9,  10])