In [234]:
import numpy as np

In [236]:
# bilangan distribusi uniform (0-1)
np.random.rand(7)

array([0.35212373, 0.14305841, 0.10663922, 0.67882477, 0.3464273 ,
       0.41535902, 0.45735124])

In [238]:
# bilangan distribusi uniform (0-1) matriks 2 dimensi
np.random.rand(5,4)

array([[0.05974795, 0.91797543, 0.80406926, 0.77806328],
       [0.05343181, 0.9445233 , 0.07248219, 0.46696193],
       [0.40828088, 0.7605533 , 0.49743631, 0.13991351],
       [0.53518166, 0.81274194, 0.19695765, 0.77826262],
       [0.65280928, 0.88633746, 0.08336361, 0.57957924]])

In [240]:
# bilangan distribusi normal (gaussion)
np.random.rand(10)

array([0.09664595, 0.73415728, 0.80530134, 0.96987291, 0.78603548,
       0.85079925, 0.76267657, 0.20429393, 0.86906006, 0.78093726])

In [242]:
# bilangan distribusi normal (gaussion) matriks 2 dimensi
np.random.rand(4,4)

array([[0.39571635, 0.49311772, 0.98505137, 0.20192107],
       [0.19030123, 0.94037661, 0.121107  , 0.38939145],
       [0.66450983, 0.97859917, 0.13192708, 0.49459049],
       [0.15440796, 0.27972537, 0.2753383 , 0.68403746]])

In [244]:
from numpy.random import rand, randn, randint

In [20]:
randn(6,2)

array([[ 1.15200072, -0.43448395],
       [ 0.31501526, -2.0502901 ],
       [ 0.30052181,  1.99252339],
       [-0.20388068, -0.49252854],
       [-0.16560687, -0.81572176],
       [-2.08198347,  0.30928838]])

In [22]:
randint(5,10) #menghasilkan random output antara 5 sampai 10

9

In [58]:
randint(0,100,20) # bilangan dari 0-100 sebanyak 20

array([98, 42,  9, 45, 73, 52, 84, 49, 77, 25,  6, 55, 60, 16, 17, 74, 35,
       31, 37, 15])

In [296]:
bilangan = randint (0,100,20).reshape(4, 5)
# create variabel untuk membuat matriks 2 dimensi

In [298]:
bilangan.reshape(4,5) #matriks 2 dimensi

array([[98, 39, 92, 99, 78],
       [56, 94, 47, 98, 28],
       [88, 30, 24, 51, 86],
       [28, 54, 15, 88,  4]])

In [300]:
bilangan.max()

99

In [302]:
bilangan.min()

4

In [304]:
bilangan.argmax()

3

In [306]:
bilangan.argmin()

19

In [308]:
bilangan.dtype

dtype('int32')

In [310]:
bilangan.shape

(4, 5)